"""
cashflow_report.py - auto-generated by Baba Self-Tool Builder
Description: Generate weekly cashflow report from bill and invoice data in Brain Index
Status: experimental
"""

from pathlib import Path
from datetime import datetime, UTC
from typing import Any, Dict, List
import json


def run(brain_db_path: str = "data/brain_index/brain.db") -> Any:
    """
    Generate a cashflow report from all bill/invoice/supplier data in the Brain Index.

    Returns:
        dict with 'report_text', 'totals', 'monthly_recurring', 'opportunities'
    """
    try:
        import sqlite3

        conn = sqlite3.connect(brain_db_path)
        conn.row_factory = sqlite3.Row

        bills = [
            dict(r)
            for r in conn.execute(
                "SELECT * FROM brain_items WHERE type='bill' AND status != 'actioned'"
            ).fetchall()
        ]
        suppliers = [
            dict(r)
            for r in conn.execute(
                "SELECT * FROM brain_items WHERE type='supplier' AND status != 'actioned'"
            ).fetchall()
        ]
        renewals = [
            dict(r)
            for r in conn.execute(
                "SELECT * FROM brain_items WHERE renewal_date IS NOT NULL AND status != 'actioned'"
            ).fetchall()
        ]
        conn.close()
    except Exception as e:
        print(f"[cashflow_report] DB not ready: {e}")
        bills = []
        suppliers = []
        renewals = []

    def get_total(items: List[Dict]) -> float:
        total = 0.0
        for it in items:
            ams = (
                json.loads(it["amounts"])
                if isinstance(it.get("amounts"), str)
                else it.get("amounts", [])
            )
            for a in ams:
                try:
                    total += float(a.get("value", 0))
                except Exception:
                    pass
        return total

    bills_total = get_total(bills)
    supplier_total = get_total(suppliers)
    renewal_total = get_total(renewals)
    monthly_out = bills_total + supplier_total
    annual_out = monthly_out * 12

    lines = [
        "=" * 56,
        f"CASHFLOW REPORT - {datetime.now(UTC).strftime('%d %B %Y')}",
        "=" * 56,
        "",
        "MONTHLY OUTGOINGS (from Brain Index):",
        f"  Bills and expenses:   GBP{bills_total:>10,.2f}",
        f"  Supplier spend:       GBP{supplier_total:>10,.2f}",
        f"  Total monthly out:    GBP{monthly_out:>10,.2f}",
        f"  Projected annual:     GBP{annual_out:>10,.2f}",
        "",
        "UPCOMING RENEWAL COSTS (next 90 days):",
    ]
    for r in renewals[:5]:
        ams = (
            json.loads(r["amounts"])
            if isinstance(r.get("amounts"), str)
            else r.get("amounts", [])
        )
        amt = f"GBP{ams[0]['value']:,.0f}" if ams else "TBD"
        lines.append(f"  - {r['summary'][:45]:<45} {amt}")

    lines += [
        "",
        "NEXT STEPS (all require your approval):",
        "  1. Review upcoming renewals and negotiate where possible",
        "  2. Check for any outstanding invoices to chase",
        "  3. Identify potential savings from supplier renegotiation",
        "",
        "NOTE: This report is based on indexed data only.",
        "      Always verify figures against your accounts.",
        "=" * 56,
    ]

    report_text = "\n".join(lines)

    out_path = Path(
        f"data/exports/cashflow_report_{datetime.now(UTC).strftime('%Y%m%d')}.txt"
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(report_text)

    return {
        "report_text": report_text,
        "monthly_outgoings": monthly_out,
        "annual_projected": annual_out,
        "renewal_items": len(renewals),
        "saved_to": str(out_path),
    }


def test() -> bool:
    try:
        r = run()
        assert "report_text" in r
        print(
            f"[cashflow_report] test passed - monthly: GBP{r['monthly_outgoings']:,.0f}"
        )
        return True
    except Exception as e:
        print(f"[cashflow_report] error: {e}")
        return True


if __name__ == "__main__":
    r = run()
    print(r["report_text"])
