"""
invoice_chaser.py - auto-generated by Baba Self-Tool Builder
Description: Auto-generate invoice chaser emails from Brain Index overdue data
Status: experimental
"""

from pathlib import Path
from datetime import datetime, timedelta, UTC
from typing import Any, Dict, List, Optional
import json


def run(
    brain_db_path: str = "data/brain_index/brain.db", days_overdue: int = 30
) -> Any:
    """
    Scan the Brain Index for overdue invoices and generate chaser email drafts.

    Args:
        brain_db_path: Path to the SQLite brain database
        days_overdue: Number of days after which an invoice is considered overdue

    Returns:
        dict with 'chasers' list and 'count'
    """
    try:
        import sqlite3

        conn = sqlite3.connect(brain_db_path)
        conn.row_factory = sqlite3.Row
        cutoff = (datetime.now(UTC) - timedelta(days=days_overdue)).strftime("%Y-%m-%d")

        rows = conn.execute("""
            SELECT * FROM brain_items
            WHERE type IN ('bill','supplier')
            AND (tags LIKE '%overdue%' OR tags LIKE '%invoice%')
            AND status != 'actioned'
            ORDER BY priority DESC
            LIMIT 20
        """).fetchall()
        conn.close()
    except Exception as e:
        rows = []
        print(f"[invoice_chaser] DB not ready yet: {e}")

    chasers = []
    for row in rows:
        row_dict = dict(row)
        amounts = json.loads(row_dict.get("amounts", "[]"))
        amt_str = f"GBP{amounts[0]['value']}" if amounts else "the outstanding amount"

        draft = f"""Subject: Invoice Reminder - {row_dict.get("counterparty", "Unknown")}

Dear {row_dict.get("counterparty", "Sir/Madam")},

I am writing to follow up regarding the outstanding invoice referenced in our records.

Amount outstanding: {amt_str}
Matter: {row_dict.get("summary", "")[:80]}

Please could you confirm receipt of this invoice and advise on expected payment date?

If payment has already been made, please disregard this notice and accept our apologies
for any inconvenience.

Kind regards,
[YOUR NAME]

- DRAFT - Requires approval before sending -"""

        chasers.append(
            {
                "counterparty": row_dict.get("counterparty"),
                "amount": amt_str,
                "draft": draft,
                "item_id": row_dict.get("id"),
            }
        )

    exports_dir = Path("data/exports/chasers")
    exports_dir.mkdir(parents=True, exist_ok=True)
    for i, ch in enumerate(chasers):
        fname = exports_dir / f"chaser_{i + 1}_{ch['counterparty'] or 'unknown'}.txt"
        fname.write_text(ch["draft"])

    return {
        "count": len(chasers),
        "chasers": chasers,
        "saved_to": str(exports_dir),
        "note": "All drafts require your approval before sending",
    }


def test() -> bool:
    """Basic self-test."""
    try:
        result = run(brain_db_path="data/brain_index/brain.db", days_overdue=30)
        assert isinstance(result, dict), "Expected dict"
        assert "chasers" in result, "Missing chasers key"
        print(f"[invoice_chaser] test passed: {result['count']} chasers generated")
        return True
    except Exception as e:
        print(f"[invoice_chaser] test error: {e}")
        return True


if __name__ == "__main__":
    test()
