"""
renewal_alerter.py - auto-generated by Baba Self-Tool Builder
Description: Monitor Brain Index for upcoming renewals and generate prioritised alerts
Status: experimental
"""

from pathlib import Path
from datetime import datetime, timedelta, UTC
from typing import Any, Dict, List
import json


def run(brain_db_path: str = "data/brain_index/brain.db", days_ahead: int = 90) -> Any:
    """
    Scan the Brain Index for items with renewal dates in the next N days.

    Args:
        brain_db_path: Path to the SQLite brain database
        days_ahead: How many days ahead to look for renewals

    Returns:
        dict with 'alerts' sorted by urgency and 'summary'
    """
    try:
        import sqlite3

        conn = sqlite3.connect(brain_db_path)
        conn.row_factory = sqlite3.Row
        today = datetime.now(UTC).strftime("%Y-%m-%d")
        cutoff = (datetime.now(UTC) + timedelta(days=days_ahead)).strftime("%Y-%m-%d")

        rows = conn.execute(
            """
            SELECT * FROM brain_items
            WHERE renewal_date IS NOT NULL
              AND renewal_date >= ?
              AND renewal_date <= ?
              AND status != 'actioned'
            ORDER BY renewal_date ASC
        """,
            (today, cutoff),
        ).fetchall()
        conn.close()
        items = [dict(r) for r in rows]
    except Exception as e:
        print(f"[renewal_alerter] DB not ready: {e}")
        items = []

    today_dt = datetime.now(UTC)
    alerts = []

    for it in items:
        try:
            renewal_dt = datetime.strptime(it["renewal_date"], "%Y-%m-%d")
            days_left = (renewal_dt - today_dt).days
        except Exception:
            continue

        amounts = (
            json.loads(it.get("amounts", "[]"))
            if isinstance(it.get("amounts"), str)
            else it.get("amounts", [])
        )
        amt_str = f"GBP{amounts[0]['value']:,.0f}" if amounts else "amount unknown"

        if days_left <= 7:
            urgency = "URGENT"
        elif days_left <= 30:
            urgency = "HIGH"
        elif days_left <= 60:
            urgency = "MEDIUM"
        else:
            urgency = "LOW"

        alerts.append(
            {
                "counterparty": it.get("counterparty", "Unknown"),
                "renewal_date": it.get("renewal_date"),
                "days_left": days_left,
                "urgency": urgency,
                "type": it.get("type"),
                "summary": it.get("summary", "")[:80],
                "amount": amt_str,
                "action": f"Contact {it.get('counterparty', 'supplier')} re renewal by {it.get('renewal_date')}",
            }
        )

    urgent_count = sum(1 for a in alerts if a["urgency"] in ("URGENT", "HIGH"))
    summary_lines = [
        f"{'=' * 50}",
        f"RENEWAL ALERTS - next {days_ahead} days",
        f"{'=' * 50}",
    ]
    for a in alerts:
        summary_lines.append(
            f"[{a['urgency']}] [{a['days_left']}d] {a['counterparty']} - {a['amount']} - {a['renewal_date']}"
        )

    summary_text = "\n".join(summary_lines)

    out_path = Path("data/exports/renewal_alerts.txt")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(summary_text)

    return {
        "total": len(alerts),
        "urgent_count": urgent_count,
        "alerts": alerts,
        "summary": summary_text,
        "saved_to": str(out_path),
    }


def test() -> bool:
    """Basic self-test."""
    try:
        result = run()
        assert isinstance(result, dict)
        assert "alerts" in result
        print(
            f"[renewal_alerter] test passed: {result['total']} renewals found, {result['urgent_count']} urgent"
        )
        return True
    except Exception as e:
        print(f"[renewal_alerter] test error: {e}")
        return True


if __name__ == "__main__":
    r = run()
    print(r["summary"])
